### List all the messages
GET http://localhost:4000/messages

### Get an existing message by ID
GET http://localhost:4000/messages/170

### Create a new message
POST http://localhost:4000/messages
content-type: application/json

{
    "content": "hi there"
}

### Get the Computer 
GET http://localhost:4000/computer

### Create a new user
POST http://localhost:4000/auth/signup
content-type: application/json

{
    "email": "development-3@example.com",
    "password": "awesomeSecret"
}

### Update a user
PATCH http://localhost:4000/auth/3
content-type: application/json

{
    "password": "newAwesomeSecret"
}

### Find all users
GET http://localhost:4000/auth/

### Find a particular user with a given email
GET http://localhost:4000/auth?email=development@example.com

### Find a particular user with a given ID
GET http://localhost:4000/auth/2

### Delete a user by ID
DELETE http://localhost:4000/auth/4
