### Create a new report
POST http://localhost:4000/reports
content-type: application/json

{
  "make": "Toyota",
  "model": "Corolla",
  "year": 1980,
  "mileage": 100000,
  "lng": 0,
  "lat": 0,
  "price": 500000
}

### Change approval of a report
PATCH http://localhost:4000/reports/4
content-type: application/json

{
  "approved": true
}
